[package]
name = "inkscape-figures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
enigo = "0.1.3"
global-hotkey = "0.4.2"
livesplit-hotkey = "0.7.0"
rdev = "0.5.3"
