[package]
name = "inkscape-figures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
global-hotkey = "0.4.2"
objc = "0.2.7"
tfc = "0.7.0"
winit = "0.29.10"
